// vue-test/src/views/Home.vue
<template>
  <div class="home-page">
    <div class="banner">
      <div class="container">
        <h1 class="logo-font">Vue-test</h1>
        <img src="img/img.png" class="container__image">
      </div>
    </div>
    <div class="container page">
      <div class="row">
        <div class="col-md-12">
          <div class="feed-toggle">
            <ul class="nav nav-pills outline-active">
              <li v-if="isAuthenticated" class="nav-item">
                <router-link
                  :to="{ name: 'home-my-feed' }"
                  class="nav-link"
                  active-class="active"
                >
                  Your Records
                </router-link>
              </li>
              <li class="nav-item">
                <router-link
                  :to="{ name: 'home' }"
                  exact
                  class="nav-link"
                  active-class="active"
                >
                  All Records
                </router-link>
              </li>
              <li class="nav-item" v-if="tag">
                <router-link
                  :to="{ name: 'home-tag', params: { tag } }"
                  class="nav-link"
                  active-class="active"
                >
                  #{{ tag }}
                </router-link>
              </li>
            </ul>
          </div>
          <router-view></router-view>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { mapGetters } from "vuex";
import { FETCH_PROFILE, FETCH_TAGS } from "@/store/actions.type";

export default {
  name: "home",
  mounted() {
    this.$store.dispatch(FETCH_PROFILE, this.$route.params);
    this.$store.dispatch(FETCH_TAGS);
  },
  computed: {
    ...mapGetters(["profile", "isAuthenticated", "tags"]),
    tag() {
      return this.$route.params.tag;
    }
  },
  watch: {
    $route(to) {
      this.$store.dispatch(FETCH_PROFILE, to.params);
    }
  }
};
</script>

// angular-test/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { ArticleListConfig, TagsService,  UserService } from '../core';

@Component({
  selector: 'app-home-page',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  constructor(
    private router: Router,
    private tagsService: TagsService,
    private userService: UserService
  ) {}

  isAuthenticated: boolean;
  listConfig: ArticleListConfig = {
    type: 'all',
    filters: {}
  };
  tags: Array<string> = [];
  tagsLoaded = false;

  ngOnInit() {
    this.userService.isAuthenticated.subscribe(
      (authenticated) => {
        this.isAuthenticated = authenticated;

        if (authenticated) {
          const username = this.userService.getCurrentUser().username;
          this.setListTo('author', {author: username});
        } else {
          this.setListTo('all');
        }
      }
    );

    this.tagsService.getAll()
    .subscribe(tags => {
      this.tags = tags;
      this.tagsLoaded = true;
    });
  }

  setListTo(type: string = '', filters: Object = {}) {

    if (type === 'author' && !this.isAuthenticated) {
      this.router.navigateByUrl('/login');
      return;
    }

    if (type === 'author') {
      const username = this.userService.getCurrentUser().username;
      this.listConfig = {type: type, filters: {author: username}};
      return;
    }

    this.listConfig = {type: type, filters: filters};
  }
}

<div class="home-page">

  <div class="banner">
    <div class="container">
      <h1 class="logo-font">Angular-test</h1>
      <img src="assets/logo.png" class="container__image">
    </div>
  </div>

  <div class="container page">
    <div class="row">

      <div class="col-md-12">
        <div class="feed-toggle">
          <ul class="nav nav-pills outline-active">
            <li class="nav-item">
              <a class="nav-link"
                 [ngClass]="{'active': listConfig.type === 'author'}"
                 (click)="setListTo('author')">
                 Your Records
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link"
                 [ngClass]="{'active': listConfig.type === 'all' && !listConfig.filters.tag}"
                 (click)="setListTo('all')">
                 All Records
              </a>
            </li>
            <li class="nav-item" [hidden]="!listConfig.filters.tag">
              <a class="nav-link active">
                <i class="ion-pound"></i> {{ listConfig.filters.tag }}
              </a>
            </li>
          </ul>
        </div>
        <app-article-list [limit]="10" [config]="listConfig"></app-article-list>
      </div>

    </div>
  </div>
</div>
